name: Build Image Self-Hosted
on:
  push:
    branches:
      - main
jobs:
  generate-labels:
    name: Generate build ID
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      build-id: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{github.repository}}



  build-image_arm:
    runs-on: self-hosted
    needs: generate-labels
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{github.repository}}
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployment/Dockerfile
          platforms: linux/arm64
          push: true
          provenance: false
          build-args: APP_NAME=split-app-backend
          tags: ${{ needs.generate-labels.outputs.tags }}, ghcr.io/${{github.repository}}:${{ needs.generate-labels.outputs.build-id }}
          labels: ${{ needs.generate-labels.outputs.tags.outputs.labels }}

  build-image-amd:
    runs-on: ubuntu-latest
    needs: generate-labels
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployment/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          build-args: APP_NAME=split-app-backend
          tags: ${{ needs.generate-labels.outputs.tags }}, ghcr.io/${{github.repository}}:${{ needs.generate-labels.outputs.build-id }}
          labels: ${{ needs.generate-labels.outputs.tags.outputs.labels }}
    
        


