name: Build Image
on:
  push:
    branches:
      - main
jobs:
  build-image:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: deployment/Dockerfile
          push: true
          tags: ${{github.repository}}:latest
          build-args: APP_NAME=split-app-backend
